### ISSUE TITLE
[Enhancement] Streamline package installs and dependencies with apt-cyg in Cygwin

### ISSUE THREAD

**Issue by Signus** [developwithpassion/devtools#3]
To improve the process of using devtools to install RVM, many users may have issues with installing the necessary packages if they do not have the Cygwin 'setup-x86_64.exe' readily available.

```
/home/user/.rvm/scripts/functions/requirements/cygwin: line 19: setup-x86_64.exe: command not found
++ return 127
Requirements installation failed with status: 127.
ruby-2.0.0-p576 is not installed.
```

My suggestion would be to add support for using (and possibly installing) apt-cyg, an apt-get 'like' utility for Cygwin, that can resolve and install any dependencies efficiently.

**Comment by signus** [comment]
Closing enhancement request.
